@startuml
skinparam classAttributeIconSize 0

package "ox.cads.testing" {

  ' ====== Solver base ======
  abstract class GenericSolver {
    + solve(events : Array<Event>) : Int
    + mkInvoke : LLInvokeEvent
    + mkReturn : LLReturnEvent
  }

  class JITLinUndoTester {
    + solve(events : Array<Event>) : Int
    + mkInvoke : LLInvokeEvent
    + mkReturn : LLReturnEvent
  }

  GenericSolver <|-- JITLinUndoTester

  ' ====== Tester principal ======
  class LinearizabilityTester {
    - mkLog : (MkInvokeType, MkReturnType) => GenericLog
    - worker : WorkerType
    - p : Int
    - iters : Int
    - concObj : Any
    - seqObj : Any
    - solver : GenericSolver
    --
    + apply() : Int
  }

  LinearizabilityTester --> GenericSolver : "usa solver"
  LinearizabilityTester --> GenericLog : "usa para recolectar eventos"

  ' Companion object como fábrica
  class LinearizabilityTesterObject <<companion>> {
    {static} JITTree(...)
    {static} WGGraph(...)
    {static} WGTree(...)
    {static} JITGraph(...)
    {static} BFSJIT(...)
  }

  LinearizabilityTesterObject ..> LinearizabilityTester : "fábrica"
  LinearizabilityTesterObject ..> JITLinUndoTester : "crea en JITTree()"
  LinearizabilityTesterObject ..> GenericLog : "SharedLog/TSLog"

  ' ====== Logs ======
  abstract class GenericLog {
    + apply(threadId : Int) : GenericThreadLog
    + getLog() : Array<Event>
  }

  class SharedLog
  class TSLog

  GenericLog <|-- SharedLog
  GenericLog <|-- TSLog

  'LinearizabilityTester --> GenericThreadLog : "worker(i, log(i))"
  'class GenericThreadLog
}

@enduml
